### ISSUE TITLE
[signup API] Error 400 "That login name is not available."

### ISSUE THREAD

**Issue by dinosoru** [smartenv-crs4/cmc-user#1]
The uniqueness test for the user email seems to check only the user segment not the whole address

**Comment by guidoyyz** [comment]
A plugin currently running in cmc-user creates a user in a CKAN running instance extracting only the left part from the mail address set in cmc-user as username. Consequently, it is the CKAN server that answers with the error 400 if there's already a user with the same username but different domain name (i.e. linetto@crs4.it vs linetto@gmail.com). We'll close this issue because the plugin will be removed in an upcoming commit, and all plugins will be stored in a separate repository.
